	SELECT nombre FROM producto;
    SELECT nombre, precio FROM producto;
    SELECT * FROM producto;
    SELECT nombre, precio AS precio_euro, ROUND(precio * 1.07,2) AS precio_dolar FROM producto;
    SELECT nombre AS nombre_producto, precio AS euro, ROUND(precio * 1.07,2) AS dolar FROM producto;
    SELECT UPPER(nombre), precio FROM producto;
    SELECT LOWER(nombre), precio FROM producto;
	SELECT nombre, UPPER(LEFT(nombre,2)) AS iniciales FROM fabricante;
    SELECT nombre, ROUND(precio,1) AS precio_redondo FROM producto;
    SELECT nombre,TRUNCATE(precio ,0) AS precio_redondo FROM producto;
    SELECT codigo_fabricante FROM producto;
    SELECT DISTINCT codigo_fabricante FROM producto;
    SELECT nombre FROM fabricante ORDER BY nombre ASC;
    SELECT nombre FROM fabricante ORDER BY nombre DESC;
    SELECT nombre, precio FROM producto ORDER BY nombre ASC, precio DESC;
	SELECT * FROM fabricante LIMIT 5;
	SELECT * FROM fabricante LIMIT 2 OFFSET 3;
	SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
	SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
    SELECT nombre FROM producto WHERE codigo_fabricante = 2;
	SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
	SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC; 
	SELECT p.codigo, p.nombre, p.codigo_fabricante, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo;
	SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio ASC LIMIT 1;
	SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY p.precio DESC LIMIT 1;
	SELECT p.*, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre = 'Lenovo'; 
	SELECT p.*, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre = 'Crucial' AND p.precio > 200; 
	SELECT p.*, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre = 'Asus'OR  f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate'; 
	SELECT p.*, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo  WHERE f.nombre IN('Asus','Hewlett-Packard','Seagate'); 
	SELECT p.nombre, p.precio FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%e';
	SELECT p.nombre, p.precio FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE f.nombre LIKE '%w%';
    SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON p.codigo_fabricante = f.codigo WHERE p.precio >= 180 ORDER BY p.precio DESC, p.nombre ASC;
	SELECT DISTINCT f.codigo, f.nombre FROM fabricante f INNER JOIN producto p ON f.codigo = p.codigo_fabricante;
	SELECT DISTINCT f.*,p.* FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante;
	SELECT DISTINCT f.* FROM fabricante f LEFT JOIN producto p ON f.codigo = p.codigo_fabricante WHERE p.codigo_fabricante IS NULL;
	SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo');
	SELECT * FROM producto WHERE precio = (SELECT precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') ORDER BY precio DESC LIMIT 1);
	SELECT nombre FROM producto WHERE precio = (SELECT precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo') ORDER BY precio DESC LIMIT 1);
	SELECT nombre FROM producto WHERE precio = (SELECT precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Hewlett-Packard') ORDER BY precio ASC LIMIT 1);
	SELECT * FROM producto WHERE precio >= (SELECT MAX(p.precio) FROM producto p WHERE p.codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
	SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus') AND precio > (SELECT AVG(p.precio) FROM producto p WHERE p.codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus'));
	SELECT p.apellido1, p.apellido2, p.nombre FROM persona p WHERE p.tipo = 'alumno' ORDER BY p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
	SELECT p.nombre, p.apellido1, p.apellido2 FROM persona p WHERE p.tipo = 'alumno' AND telefono IS NULL;
	SELECT * FROM persona p WHERE p.tipo = 'alumno' AND YEAR(p.fecha_nacimiento) = 1999; 
	SELECT * FROM persona p WHERE p.tipo = 'profesor' AND telefono IS NULL AND p.nif LIKE '%k';
	SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
	SELECT p.apellido1, p.apellido2, p.nombre,d.nombre FROM persona p INNER JOIN profesor prof ON p.id = prof.id_profesor INNER JOIN departamento d ON prof.id_departamento = d.id ORDER BY p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
	SELECT a.nombre, c.anyo_inicio, c.anyo_fin FROM curso_escolar c INNER JOIN alumno_se_matricula_asignatura matri ON c.id = matri.id_curso_escolar INNER JOIN persona p ON matri.id_alumno = p.id  INNER JOIN asignatura a ON matri.id_asignatura = a.id WHERE p.nif = '26902806M';
	SELECT DISTINCT d.nombre FROM departamento d INNER JOIN profesor p ON d.id = p.id_departamento INNER JOIN asignatura a ON p.id_profesor = a.id_profesor WHERE a.id_grado = 4;
	SELECT DISTINCT p.nombre, p.apellido1, p.apellido2 FROM persona p JOIN alumno_se_matricula_asignatura m ON p.id = m.id_alumno JOIN curso_escolar c ON m.id_curso_escolar = c.id WHERE p.tipo = 'alumno' AND c.anyo_inicio = 2018 AND c.anyo_fin = 2019;
    SELECT d.nombre AS departamento, p.apellido1, p.apellido2, p.nombre AS nombre_profesor FROM persona p INNER JOIN profesor prof ON p.id = prof.id_profesor LEFT JOIN departamento d ON prof.id_departamento = d.id ORDER BY d.nombre ASC, p.apellido1 ASC, p.apellido2 ASC, p.nombre ASC;
	SELECT p.nombre AS nombre_profesor FROM persona p LEFT JOIN profesor prof ON p.id = prof.id_profesor WHERE prof.id_departamento IS NULL;
	SELECT d.nombre AS departamento FROM departamento d LEFT JOIN profesor prof ON d.id = prof.id_departamento WHERE prof.id_profesor IS NULL;
	SELECT p.nombre FROM persona p JOIN profesor prof ON p.id = prof.id_profesor LEFT JOIN asignatura a ON prof.id_profesor = a.id_profesor WHERE a.id_profesor IS NULL;
	SELECT a.nombre FROM profesor p RIGHT JOIN asignatura a ON p.id_profesor = a.id_profesor WHERE p.id_profesor IS NULL;
	SELECT d.nombre FROM departamento d LEFT JOIN ( SELECT DISTINCT prof.id_departamento FROM profesor prof INNER JOIN asignatura a ON prof.id_profesor = a.id_profesor) AS departamento_con_asignatura ON d.id = departamento_con_asignatura.id_departamento WHERE departamento_con_asignatura;
	SELECT COUNT(*) AS numero_alumnos FROM persona WHERE tipo = 'alumno';
	SELECT COUNT(*) AS numero_alumnos_1999 FROM persona WHERE tipo = 'alumno' AND YEAR(fecha_nacimiento) = 1999;
	SELECT d.nombre AS nombre_departamento, COUNT(p.id_profesor) AS num_profesores_departamento FROM profesor p JOIN departamento d ON p.id_departamento = d.id GROUP BY d.nombre ORDER BY num_profesores_departamento DESC;
	SELECT d.nombre AS nombre_departamento, COUNT(p.id_profesor) AS num_profesores_departamento FROM profesor p RIGHT JOIN departamento d ON p.id_departamento = d.id GROUP BY d.nombre ORDER BY num_profesores_departamento DESC;
	SELECT g.nombre AS nombre_grado, COUNT(a.id_grado) AS numero_asignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.id ORDER BY numero_asignaturas DESC;
    SELECT g.nombre, COUNT(a.id_grado) AS num_asignaturas FROM grado g LEFT JOIN asignatura a ON g.id = a.id_grado GROUP BY g.nombre HAVING num_asignaturas > 40; 